app:
  name: base-system
  version: 0.0.1
  copyrightYear: 2022
  demoEnabled: false
  profile: /path/to/upload
  addressEnabled: true
  captchaType: math

server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    threads:
      max: 200
      min-spare: 100

logging:
  level:
    com.yankaizhang: debug
    org.springframework: warn

spring:
  messages:
    basename: i18n/messages
  profiles:
    active: druid
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms

token:
  header: Authorization
  secret: abcdefghijklmnopqrstuvwxyz
  expireTime: 30

mybatis:
  typeAliasesPackage: com.yankaizhang.project.**.domain
  mapperLocations: classpath*:mybatis/**/*Mapper.xml
  configLocation: classpath:mybatis/mybatis-config.xml

pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

xss:
  enabled: true
  excludes:
  urlPatterns: /system/*,/monitor/*,/tool/*
